// <auto-generated />
namespace WebChat.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addindices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addindices));
        
        string IMigrationMetadata.Id
        {
            get { return "201308142123319_Add indices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
